id: P010526
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:54:19.047569
source_metadata:
  id: bdr:W1GS61415
  title: མཁན་ཆེན་ཁྲོ་རུ་ཚེ་རྣམ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    14692b205af247a6ab3ea7fc677ee24b:
      image_group_id: I1GS61417
      title: ''
      volume_number: 1
      total_pages: 151
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
