id: I4A939CA9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:32:20+00:00'
last_modified: '2022-06-08T14:15:22.594042+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS61415
  title: མཁན་ཆེན་ཁྲོ་རུ་ཚེ་རྣམ་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    888D:
      image_group_id: I1GS61417
      title: ''
      total_pages: 151
      order: 1
      base_file: 888D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
